apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: whoami
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rajatjindal/kubectl-whoami
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-whoami/releases/download/{{ .TagName }}/kubectl-whoami_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-whoami
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-whoami/releases/download/{{ .TagName }}/kubectl-whoami_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    files:
    - from: "*"
      to: "."
    bin: kubectl-whoami
  shortDescription: Show the subject that's currently authenticated as.
  description: |
    This plugin show the subject that's currently authenticated as.

