apiVersion: krew.googlecontainertools.github.com/v1alpha2
kind: Plugin
metadata:
  name: emitevent
spec:
  version: {{ .TagName }}
  homepage: https://github.com/rajatjindal/kubectl-emitevent
  platforms:
  - selector:
      matchLabels:
        os: darwin
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-emitevent/releases/download/{{ .TagName }}/kubectl-emitevent_{{ .TagName }}_darwin_amd64.tar.gz" .TagName }}
    bin: kubectl-emitevent
  - selector:
      matchLabels:
        os: linux
        arch: amd64
    {{addURIAndSha "https://github.com/rajatjindal/kubectl-emitevent/releases/download/{{ .TagName }}/kubectl-emitevent_{{ .TagName }}_linux_amd64.tar.gz" .TagName }}
    bin: kubectl-emitevent
  shortDescription: Emit Kubernetes Events for the requested object
  description: |
    This plugin emits the Kubernetes Events for the requested object

